FROM rust:1.55-slim-bullseye as builder

# Install build dependencies
RUN mkdir /ygame/

# Copy Files
WORKDIR /ygame/
COPY ./misc/Cargo.server.toml /ygame/Cargo.toml
COPY ./game/Cargo.toml /ygame/game/
COPY ./game/src/ /ygame/game/src/
COPY ./protocol/Cargo.toml /ygame/protocol/
COPY ./protocol/src/ /ygame/protocol/src/
COPY ./server/Cargo.toml ./server/Cargo.lock /ygame/server/
COPY ./server/src/ /ygame/server/src/

# Build the project
RUN cargo build --release

FROM debian:bullseye-slim
ARG APP=

EXPOSE 8000

ENV TZ=Etc/UTC \
    APP_USER=ygame

RUN groupadd $APP_USER \
    && useradd -g $APP_USER $APP_USER \
    && mkdir -p /usr/local/ygame

COPY --from=builder /ygame/target/release/ygame /usr/local/ygame/ygame

RUN chown -R $APP_USER:$APP_USER /usr/local/ygame

USER $APP_USER
WORKDIR /usr/local/ygame

CMD ["/usr/local/ygame/ygame", "-l", "0.0.0.0", "-p", "8000", "-vvv"]

