version: "3.9"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile_server
    ports:
      - "8000:8000"
      
  nginx:
    build:
      context: .
      dockerfile: Dockerfile_nginx
    ports:
      - "5000:80"
    links:
      - "server:gameserver"
